apiVersion: v1
kind: Pod
metadata:
  generateName: nri-test-
  labels:
    type: interactive
    research-group: rl-team
spec:
  hostIPC: true
  restartPolicy: Never
  containers:
  - name: nri-train
    command: ["python", "-u", "test.py", 
    "--suffix=_dance", 
    "--num-atoms=53",
    "--prediction-steps=10",
    "--dims=6",
    "--edge-types=4",
    "--encoder=mlp",
    "--decoder=rnn",
    "--dynamic-graph",
    "--skip-first",
#     "--hard",
    "--save-folder=/workspace/NRI/logs/dance_53joints_rnndecoder",
    "--timestamp=exp2020-07-09T18:07:56.912779",
  ]
    # command: ["sleep", "infinity"]
    image: amr-registry.caas.intel.com/aipg/mpettee-nri
    workingDir: /workspace/NRI/
    resources:
      limits:
        nvidia.com/gpu: 0
        cpu: 1
        memory: 300Gi
    volumeMounts:
    - mountPath: "/workspace"
      name: workspace 
    envFrom:
    - configMapRef:
        name: proxy-config
    env:
    - name: LD_LIBRARY_PATH
      value: $LD_LIBRARY_PATH:/.mujoco/mjpro150/bin
    - name: OMP_NUM_THREADS
      value: "1"
  securityContext:
    fsGroup: 17685
    runAsUser: 11964579
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: workdisk

